// NeetCode 250 Questions - Official List
const questions = [
  // Arrays & Hashing (22)
  {
    id: 1929,
    title: "Concatenation of Array",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  {
    id: 217,
    title: "Contains Duplicate",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  {
    id: 242,
    title: "Valid Anagram",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  { id: 1, title: "Two Sum", difficulty: "Easy", category: "Arrays & Hashing" },
  {
    id: 14,
    title: "Longest Common Prefix",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  {
    id: 49,
    title: "Group Anagrams",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 27,
    title: "Remove Element",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  {
    id: 169,
    title: "Majority Element",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  {
    id: 705,
    title: "Design HashSet",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  {
    id: 706,
    title: "Design HashMap",
    difficulty: "Easy",
    category: "Arrays & Hashing",
  },
  {
    id: 912,
    title: "Sort an Array",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 75,
    title: "Sort Colors",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 347,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 271,
    title: "Encode and Decode Strings",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 304,
    title: "Range Sum Query 2D Immutable",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 238,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 36,
    title: "Valid Sudoku",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 128,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 122,
    title: "Best Time to Buy And Sell Stock II",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 229,
    title: "Majority Element II",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 560,
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    category: "Arrays & Hashing",
  },
  {
    id: 41,
    title: "First Missing Positive",
    difficulty: "Hard",
    category: "Arrays & Hashing",
  },

  // Two Pointers (13)
  {
    id: 344,
    title: "Reverse String",
    difficulty: "Easy",
    category: "Two Pointers",
  },
  {
    id: 125,
    title: "Valid Palindrome",
    difficulty: "Easy",
    category: "Two Pointers",
  },
  {
    id: 680,
    title: "Valid Palindrome II",
    difficulty: "Easy",
    category: "Two Pointers",
  },
  {
    id: 1768,
    title: "Merge Strings Alternately",
    difficulty: "Easy",
    category: "Two Pointers",
  },
  {
    id: 88,
    title: "Merge Sorted Array",
    difficulty: "Easy",
    category: "Two Pointers",
  },
  {
    id: 26,
    title: "Remove Duplicates From Sorted Array",
    difficulty: "Easy",
    category: "Two Pointers",
  },
  {
    id: 167,
    title: "Two Sum II Input Array Is Sorted",
    difficulty: "Medium",
    category: "Two Pointers",
  },
  { id: 15, title: "3Sum", difficulty: "Medium", category: "Two Pointers" },
  { id: 18, title: "4Sum", difficulty: "Medium", category: "Two Pointers" },
  {
    id: 189,
    title: "Rotate Array",
    difficulty: "Medium",
    category: "Two Pointers",
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    category: "Two Pointers",
  },
  {
    id: 881,
    title: "Boats to Save People",
    difficulty: "Medium",
    category: "Two Pointers",
  },
  {
    id: 42,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    category: "Two Pointers",
  },

  // Sliding Window (9)
  {
    id: 219,
    title: "Contains Duplicate II",
    difficulty: "Easy",
    category: "Sliding Window",
  },
  {
    id: 121,
    title: "Best Time to Buy And Sell Stock",
    difficulty: "Easy",
    category: "Sliding Window",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    category: "Sliding Window",
  },
  {
    id: 424,
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    category: "Sliding Window",
  },
  {
    id: 567,
    title: "Permutation In String",
    difficulty: "Medium",
    category: "Sliding Window",
  },
  {
    id: 209,
    title: "Minimum Size Subarray Sum",
    difficulty: "Medium",
    category: "Sliding Window",
  },
  {
    id: 658,
    title: "Find K Closest Elements",
    difficulty: "Medium",
    category: "Sliding Window",
  },
  {
    id: 76,
    title: "Minimum Window Substring",
    difficulty: "Hard",
    category: "Sliding Window",
  },
  {
    id: 239,
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    category: "Sliding Window",
  },

  // Stack (14)
  { id: 682, title: "Baseball Game", difficulty: "Easy", category: "Stack" },
  { id: 20, title: "Valid Parentheses", difficulty: "Easy", category: "Stack" },
  {
    id: 225,
    title: "Implement Stack Using Queues",
    difficulty: "Easy",
    category: "Stack",
  },
  {
    id: 232,
    title: "Implement Queue using Stacks",
    difficulty: "Easy",
    category: "Stack",
  },
  { id: 155, title: "Min Stack", difficulty: "Medium", category: "Stack" },
  {
    id: 150,
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    category: "Stack",
  },
  {
    id: 735,
    title: "Asteroid Collision",
    difficulty: "Medium",
    category: "Stack",
  },
  {
    id: 739,
    title: "Daily Temperatures",
    difficulty: "Medium",
    category: "Stack",
  },
  {
    id: 901,
    title: "Online Stock Span",
    difficulty: "Medium",
    category: "Stack",
  },
  { id: 853, title: "Car Fleet", difficulty: "Medium", category: "Stack" },
  { id: 71, title: "Simplify Path", difficulty: "Medium", category: "Stack" },
  { id: 394, title: "Decode String", difficulty: "Medium", category: "Stack" },
  {
    id: 895,
    title: "Maximum Frequency Stack",
    difficulty: "Hard",
    category: "Stack",
  },
  {
    id: 84,
    title: "Largest Rectangle In Histogram",
    difficulty: "Hard",
    category: "Stack",
  },

  // Binary Search (14)
  {
    id: 704,
    title: "Binary Search",
    difficulty: "Easy",
    category: "Binary Search",
  },
  {
    id: 35,
    title: "Search Insert Position",
    difficulty: "Easy",
    category: "Binary Search",
  },
  {
    id: 374,
    title: "Guess Number Higher Or Lower",
    difficulty: "Easy",
    category: "Binary Search",
  },
  { id: 69, title: "Sqrt(x)", difficulty: "Easy", category: "Binary Search" },
  {
    id: 74,
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    category: "Binary Search",
  },
  {
    id: 875,
    title: "Koko Eating Bananas",
    difficulty: "Medium",
    category: "Binary Search",
  },
  {
    id: 1011,
    title: "Capacity to Ship Packages Within D Days",
    difficulty: "Medium",
    category: "Binary Search",
  },
  {
    id: 153,
    title: "Find Minimum In Rotated Sorted Array",
    difficulty: "Medium",
    category: "Binary Search",
  },
  {
    id: 33,
    title: "Search In Rotated Sorted Array",
    difficulty: "Medium",
    category: "Binary Search",
  },
  {
    id: 81,
    title: "Search In Rotated Sorted Array II",
    difficulty: "Medium",
    category: "Binary Search",
  },
  {
    id: 981,
    title: "Time Based Key Value Store",
    difficulty: "Medium",
    category: "Binary Search",
  },
  {
    id: 410,
    title: "Split Array Largest Sum",
    difficulty: "Hard",
    category: "Binary Search",
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    category: "Binary Search",
  },
  {
    id: 1095,
    title: "Find in Mountain Array",
    difficulty: "Hard",
    category: "Binary Search",
  },

  // Linked List (14)
  {
    id: 206,
    title: "Reverse Linked List",
    difficulty: "Easy",
    category: "Linked List",
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    category: "Linked List",
  },
  {
    id: 141,
    title: "Linked List Cycle",
    difficulty: "Easy",
    category: "Linked List",
  },
  {
    id: 143,
    title: "Reorder List",
    difficulty: "Medium",
    category: "Linked List",
  },
  {
    id: 19,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    category: "Linked List",
  },
  {
    id: 138,
    title: "Copy List With Random Pointer",
    difficulty: "Medium",
    category: "Linked List",
  },
  {
    id: 2,
    title: "Add Two Numbers",
    difficulty: "Medium",
    category: "Linked List",
  },
  {
    id: 287,
    title: "Find The Duplicate Number",
    difficulty: "Medium",
    category: "Linked List",
  },
  {
    id: 92,
    title: "Reverse Linked List II",
    difficulty: "Medium",
    category: "Linked List",
  },
  {
    id: 622,
    title: "Design Circular Queue",
    difficulty: "Medium",
    category: "Linked List",
  },
  {
    id: 146,
    title: "LRU Cache",
    difficulty: "Medium",
    category: "Linked List",
  },
  { id: 460, title: "LFU Cache", difficulty: "Hard", category: "Linked List" },
  {
    id: 23,
    title: "Merge K Sorted Lists",
    difficulty: "Hard",
    category: "Linked List",
  },
  {
    id: 25,
    title: "Reverse Nodes In K Group",
    difficulty: "Hard",
    category: "Linked List",
  },

  // Trees (23)
  {
    id: 94,
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    category: "Trees",
  },
  {
    id: 144,
    title: "Binary Tree Preorder Traversal",
    difficulty: "Easy",
    category: "Trees",
  },
  {
    id: 145,
    title: "Binary Tree Postorder Traversal",
    difficulty: "Easy",
    category: "Trees",
  },
  {
    id: 226,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    category: "Trees",
  },
  {
    id: 104,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    category: "Trees",
  },
  {
    id: 543,
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    category: "Trees",
  },
  {
    id: 110,
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    category: "Trees",
  },
  { id: 100, title: "Same Tree", difficulty: "Easy", category: "Trees" },
  {
    id: 572,
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    category: "Trees",
  },
  {
    id: 235,
    title: "Lowest Common Ancestor of a Binary Search Tree",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 701,
    title: "Insert into a Binary Search Tree",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 450,
    title: "Delete Node in a BST",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 102,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 199,
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 427,
    title: "Construct Quad Tree",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 1448,
    title: "Count Good Nodes In Binary Tree",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 98,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 230,
    title: "Kth Smallest Element In a Bst",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 105,
    title: "Construct Binary Tree From Preorder And Inorder Traversal",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 337,
    title: "House Robber III",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 1325,
    title: "Delete Leaves With a Given Value",
    difficulty: "Medium",
    category: "Trees",
  },
  {
    id: 124,
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    category: "Trees",
  },
  {
    id: 297,
    title: "Serialize And Deserialize Binary Tree",
    difficulty: "Hard",
    category: "Trees",
  },

  // Heap / Priority Queue (12)
  {
    id: 703,
    title: "Kth Largest Element In a Stream",
    difficulty: "Easy",
    category: "Heap / Priority Queue",
  },
  {
    id: 1046,
    title: "Last Stone Weight",
    difficulty: "Easy",
    category: "Heap / Priority Queue",
  },
  {
    id: 973,
    title: "K Closest Points to Origin",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 215,
    title: "Kth Largest Element In An Array",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 621,
    title: "Task Scheduler",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 355,
    title: "Design Twitter",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 1834,
    title: "Single Threaded CPU",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 767,
    title: "Reorganize String",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 1405,
    title: "Longest Happy String",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 1094,
    title: "Car Pooling",
    difficulty: "Medium",
    category: "Heap / Priority Queue",
  },
  {
    id: 295,
    title: "Find Median From Data Stream",
    difficulty: "Hard",
    category: "Heap / Priority Queue",
  },
  {
    id: 502,
    title: "IPO",
    difficulty: "Hard",
    category: "Heap / Priority Queue",
  },

  // Backtracking (17)
  {
    id: 1863,
    title: "Sum of All Subsets XOR Total",
    difficulty: "Easy",
    category: "Backtracking",
  },
  { id: 78, title: "Subsets", difficulty: "Medium", category: "Backtracking" },
  {
    id: 39,
    title: "Combination Sum",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 40,
    title: "Combination Sum II",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 77,
    title: "Combinations",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 46,
    title: "Permutations",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 90,
    title: "Subsets II",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 47,
    title: "Permutations II",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 22,
    title: "Generate Parentheses",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 79,
    title: "Word Search",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 131,
    title: "Palindrome Partitioning",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 17,
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 473,
    title: "Matchsticks to Square",
    difficulty: "Medium",
    category: "Backtracking",
  },
  {
    id: 698,
    title: "Partition to K Equal Sum Subsets",
    difficulty: "Medium",
    category: "Backtracking",
  },
  { id: 51, title: "N Queens", difficulty: "Hard", category: "Backtracking" },
  {
    id: 52,
    title: "N Queens II",
    difficulty: "Hard",
    category: "Backtracking",
  },
  {
    id: 140,
    title: "Word Break II",
    difficulty: "Hard",
    category: "Backtracking",
  },

  // Tries (4)
  {
    id: 208,
    title: "Implement Trie Prefix Tree",
    difficulty: "Medium",
    category: "Tries",
  },
  {
    id: 211,
    title: "Design Add And Search Words Data Structure",
    difficulty: "Medium",
    category: "Tries",
  },
  {
    id: 2707,
    title: "Extra Characters in a String",
    difficulty: "Medium",
    category: "Tries",
  },
  { id: 212, title: "Word Search II", difficulty: "Hard", category: "Tries" },

  // Graphs (21)
  {
    id: 463,
    title: "Island Perimeter",
    difficulty: "Easy",
    category: "Graphs",
  },
  {
    id: 953,
    title: "Verifying An Alien Dictionary",
    difficulty: "Easy",
    category: "Graphs",
  },
  {
    id: 997,
    title: "Find the Town Judge",
    difficulty: "Easy",
    category: "Graphs",
  },
  {
    id: 200,
    title: "Number of Islands",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 695,
    title: "Max Area of Island",
    difficulty: "Medium",
    category: "Graphs",
  },
  { id: 133, title: "Clone Graph", difficulty: "Medium", category: "Graphs" },
  {
    id: 286,
    title: "Walls And Gates",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 994,
    title: "Rotting Oranges",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 417,
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 130,
    title: "Surrounded Regions",
    difficulty: "Medium",
    category: "Graphs",
  },
  { id: 752, title: "Open The Lock", difficulty: "Medium", category: "Graphs" },
  {
    id: 207,
    title: "Course Schedule",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 210,
    title: "Course Schedule II",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 261,
    title: "Graph Valid Tree",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 1462,
    title: "Course Schedule IV",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 323,
    title: "Number of Connected Components In An Undirected Graph",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 684,
    title: "Redundant Connection",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 721,
    title: "Accounts Merge",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 399,
    title: "Evaluate Division",
    difficulty: "Medium",
    category: "Graphs",
  },
  {
    id: 310,
    title: "Minimum Height Trees",
    difficulty: "Medium",
    category: "Graphs",
  },
  { id: 127, title: "Word Ladder", difficulty: "Hard", category: "Graphs" },

  // Advanced Graphs (10)
  {
    id: 1631,
    title: "Path with Minimum Effort",
    difficulty: "Medium",
    category: "Advanced Graphs",
  },
  {
    id: 743,
    title: "Network Delay Time",
    difficulty: "Medium",
    category: "Advanced Graphs",
  },
  {
    id: 332,
    title: "Reconstruct Itinerary",
    difficulty: "Hard",
    category: "Advanced Graphs",
  },
  {
    id: 1584,
    title: "Min Cost to Connect All Points",
    difficulty: "Medium",
    category: "Advanced Graphs",
  },
  {
    id: 778,
    title: "Swim In Rising Water",
    difficulty: "Hard",
    category: "Advanced Graphs",
  },
  {
    id: 269,
    title: "Alien Dictionary",
    difficulty: "Hard",
    category: "Advanced Graphs",
  },
  {
    id: 787,
    title: "Cheapest Flights Within K Stops",
    difficulty: "Medium",
    category: "Advanced Graphs",
  },
  {
    id: 1489,
    title: "Find Critical and Pseudo Critical Edges in Minimum Spanning Tree",
    difficulty: "Hard",
    category: "Advanced Graphs",
  },
  {
    id: 2392,
    title: "Build a Matrix With Conditions",
    difficulty: "Hard",
    category: "Advanced Graphs",
  },
  {
    id: 2709,
    title: "Greatest Common Divisor Traversal",
    difficulty: "Hard",
    category: "Advanced Graphs",
  },

  // 1-D Dynamic Programming (17)
  {
    id: 70,
    title: "Climbing Stairs",
    difficulty: "Easy",
    category: "1-D Dynamic Programming",
  },
  {
    id: 746,
    title: "Min Cost Climbing Stairs",
    difficulty: "Easy",
    category: "1-D Dynamic Programming",
  },
  {
    id: 1137,
    title: "N-th Tribonacci Number",
    difficulty: "Easy",
    category: "1-D Dynamic Programming",
  },
  {
    id: 198,
    title: "House Robber",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 213,
    title: "House Robber II",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 647,
    title: "Palindromic Substrings",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 91,
    title: "Decode Ways",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 322,
    title: "Coin Change",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 152,
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 139,
    title: "Word Break",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 300,
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 416,
    title: "Partition Equal Subset Sum",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 377,
    title: "Combination Sum IV",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 279,
    title: "Perfect Squares",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 343,
    title: "Integer Break",
    difficulty: "Medium",
    category: "1-D Dynamic Programming",
  },
  {
    id: 1406,
    title: "Stone Game III",
    difficulty: "Hard",
    category: "1-D Dynamic Programming",
  },

  // 2-D Dynamic Programming (16)
  {
    id: 62,
    title: "Unique Paths",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 63,
    title: "Unique Paths II",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 64,
    title: "Minimum Path Sum",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 1143,
    title: "Longest Common Subsequence",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 1049,
    title: "Last Stone Weight II",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 309,
    title: "Best Time to Buy And Sell Stock With Cooldown",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 518,
    title: "Coin Change II",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 494,
    title: "Target Sum",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 97,
    title: "Interleaving String",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 877,
    title: "Stone Game",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 1140,
    title: "Stone Game II",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 329,
    title: "Longest Increasing Path In a Matrix",
    difficulty: "Hard",
    category: "2-D Dynamic Programming",
  },
  {
    id: 115,
    title: "Distinct Subsequences",
    difficulty: "Hard",
    category: "2-D Dynamic Programming",
  },
  {
    id: 72,
    title: "Edit Distance",
    difficulty: "Medium",
    category: "2-D Dynamic Programming",
  },
  {
    id: 312,
    title: "Burst Balloons",
    difficulty: "Hard",
    category: "2-D Dynamic Programming",
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    difficulty: "Hard",
    category: "2-D Dynamic Programming",
  },

  // Greedy (14)
  { id: 860, title: "Lemonade Change", difficulty: "Easy", category: "Greedy" },
  {
    id: 53,
    title: "Maximum Subarray",
    difficulty: "Medium",
    category: "Greedy",
  },
  {
    id: 918,
    title: "Maximum Sum Circular Subarray",
    difficulty: "Medium",
    category: "Greedy",
  },
  {
    id: 978,
    title: "Longest Turbulent Subarray",
    difficulty: "Medium",
    category: "Greedy",
  },
  { id: 55, title: "Jump Game", difficulty: "Medium", category: "Greedy" },
  { id: 45, title: "Jump Game II", difficulty: "Medium", category: "Greedy" },
  {
    id: 1871,
    title: "Jump Game VII",
    difficulty: "Medium",
    category: "Greedy",
  },
  { id: 134, title: "Gas Station", difficulty: "Medium", category: "Greedy" },
  {
    id: 846,
    title: "Hand of Straights",
    difficulty: "Medium",
    category: "Greedy",
  },
  { id: 649, title: "Dota2 Senate", difficulty: "Medium", category: "Greedy" },
  {
    id: 1899,
    title: "Merge Triplets to Form Target Triplet",
    difficulty: "Medium",
    category: "Greedy",
  },
  {
    id: 763,
    title: "Partition Labels",
    difficulty: "Medium",
    category: "Greedy",
  },
  {
    id: 678,
    title: "Valid Parenthesis String",
    difficulty: "Medium",
    category: "Greedy",
  },
  { id: 135, title: "Candy", difficulty: "Hard", category: "Greedy" },

  // Intervals (7)
  {
    id: 57,
    title: "Insert Interval",
    difficulty: "Medium",
    category: "Intervals",
  },
  {
    id: 56,
    title: "Merge Intervals",
    difficulty: "Medium",
    category: "Intervals",
  },
  {
    id: 435,
    title: "Non Overlapping Intervals",
    difficulty: "Medium",
    category: "Intervals",
  },
  {
    id: 252,
    title: "Meeting Rooms",
    difficulty: "Easy",
    category: "Intervals",
  },
  {
    id: 253,
    title: "Meeting Rooms II",
    difficulty: "Medium",
    category: "Intervals",
  },
  {
    id: 2402,
    title: "Meeting Rooms III",
    difficulty: "Hard",
    category: "Intervals",
  },
  {
    id: 1851,
    title: "Minimum Interval to Include Each Query",
    difficulty: "Hard",
    category: "Intervals",
  },

  // Math & Geometry (13)
  {
    id: 168,
    title: "Excel Sheet Column Title",
    difficulty: "Easy",
    category: "Math & Geometry",
  },
  {
    id: 1071,
    title: "Greatest Common Divisor of Strings",
    difficulty: "Easy",
    category: "Math & Geometry",
  },
  {
    id: 2807,
    title: "Insert Greatest Common Divisors in Linked List",
    difficulty: "Medium",
    category: "Math & Geometry",
  },
  {
    id: 867,
    title: "Transpose Matrix",
    difficulty: "Easy",
    category: "Math & Geometry",
  },
  {
    id: 48,
    title: "Rotate Image",
    difficulty: "Medium",
    category: "Math & Geometry",
  },
  {
    id: 54,
    title: "Spiral Matrix",
    difficulty: "Medium",
    category: "Math & Geometry",
  },
  {
    id: 73,
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    category: "Math & Geometry",
  },
  {
    id: 202,
    title: "Happy Number",
    difficulty: "Easy",
    category: "Math & Geometry",
  },
  {
    id: 66,
    title: "Plus One",
    difficulty: "Easy",
    category: "Math & Geometry",
  },
  {
    id: 13,
    title: "Roman to Integer",
    difficulty: "Easy",
    category: "Math & Geometry",
  },
  {
    id: 50,
    title: "Pow(x, n)",
    difficulty: "Medium",
    category: "Math & Geometry",
  },
  {
    id: 43,
    title: "Multiply Strings",
    difficulty: "Medium",
    category: "Math & Geometry",
  },
  {
    id: 2013,
    title: "Detect Squares",
    difficulty: "Medium",
    category: "Math & Geometry",
  },

  // Bit Manipulation (10)
  {
    id: 136,
    title: "Single Number",
    difficulty: "Easy",
    category: "Bit Manipulation",
  },
  {
    id: 191,
    title: "Number of 1 Bits",
    difficulty: "Easy",
    category: "Bit Manipulation",
  },
  {
    id: 338,
    title: "Counting Bits",
    difficulty: "Easy",
    category: "Bit Manipulation",
  },
  {
    id: 67,
    title: "Add Binary",
    difficulty: "Easy",
    category: "Bit Manipulation",
  },
  {
    id: 190,
    title: "Reverse Bits",
    difficulty: "Easy",
    category: "Bit Manipulation",
  },
  {
    id: 268,
    title: "Missing Number",
    difficulty: "Easy",
    category: "Bit Manipulation",
  },
  {
    id: 371,
    title: "Sum of Two Integers",
    difficulty: "Medium",
    category: "Bit Manipulation",
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Medium",
    category: "Bit Manipulation",
  },
  {
    id: 201,
    title: "Bitwise AND of Numbers Range",
    difficulty: "Medium",
    category: "Bit Manipulation",
  },
  {
    id: 3133,
    title: "Minimum Array End",
    difficulty: "Medium",
    category: "Bit Manipulation",
  },
]

// Log count for verification
console.log(`NeetCode 250 loaded: ${questions.length} questions`)

